import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
    es: {
      appName: "Árbol IoT",
      alertSorry: 'Lo sentimos',
      acceptLabel: 'Aceptar', 
      continueLabel: 'Continuar',
      noSpecie: 'Sin especie',
      description: 'Descripción',
      numbers: 'El campo "{0}" debe ser un número válido',
      email: 'El campo "{0}" debe ser un correo electrónico válido',
      required: 'El campo "{0}" es requerido',
      date: 'El campo "{0}" debe contener una fecha válida ({1})',
      minlength: 'La longitud del campo "{0}" debe ser mayor que {1} caracteres',
      maxlength: 'La longitud del campo "{0}" debe ser menor que {1} caracteres',
      diameterMinNumber: 'Debes ingresar un número mayor a 0 para el campo {0}',
      nextLabel: 'Siguiente',
      backLabel: 'Regresar',
      finish: 'Terminar',
      retry: 'Intentar nuevamente',
      exit: 'Salir',
      asc: 'Ascendente',
      desc: 'Descendente',
      ok: 'Aceptar',
      search: 'Buscar por colonia',
      emptyList: "No hay resultados",
      leaveOnBoard: "¿Estás seguro que deseas saltar el tutorial?",
      leaveOnBoardMsg: 'Al saltar el tutorial no ganarás los puntos asignados para este módulo. ',
      continueLabelOnBoard: 'Seguir con el tutorial',
      leaveLabel: 'Saltar',
      seasons: {
         WINTER_SOLSTICE: 'Invierno',
         AUTUMNAL_EQUINOX: 'Otoño',
         SUMMER_SOLSTICE: 'Verano',
         VERNAL_EQUINOX: 'Primavera'
      },
      closeReasons:{
         INAPPROPRIATE_CONTENT: "Contenido inapropiado",
         TOPIC_RESOLVED: "Tema resuelto",
         INACTIVITY: "Inactividad",
         OTHER: "Otro",
      },
      policyDownReasons:{
         CREATION_OF_FALSE_CONTENT: "Creación de contenido falso",
         INACTIVITY: "Inactividad", 
         OTHER: "Otro"         
      },     
      globalErrors: {
         connection: "Error de conexión",
         mailNotFound: "Correo electrónico no encontrado",
         gamProfile: "Perfil de gamificación no encontrado"
      },  
      imagePicker: {
         changePhoto: "Seleccionar foto",
         cancelPhoto: "Cancelar",
         library: "Galería",
         camera: "Cámara",
         error: 'No se ha podido subir la imagen, intenta con una diferente o vuelve más tarde',
         uploadGeneral: 'Se ha adjuntado la foto',
         upload: 'Se ha adjuntado la foto de la estación actual',
         update: 'Se ha actualizado la foto de la estación actual',
         extension: 'Solo se permiten archivos con extensión jpg y png'
      },
      imagepicker:{
         changePhoto: 'Cambiar fotografía',
         cancelPhoto: "Cancelar",
         library: "Galería",
         camera: "Cámara",
      },
      general: {
         error: 'Se ha encontrado un error al intentar realizar la operación, intenta de nuevo o regresa más tarde',
         location: 'SELECCIONAR LOCALIZACIÓN',
         confirmationSave: "Los datos se actualizaron de manera correcta",
         confirmationAdoption: "Árbol adoptado, puedes revisar el estado de tu nuevo árbol en el apartado mis árboles",
      },
      fieldsValidations: {
         mail: "correo",
         password: "contraseña",
         repeatPassword: "confirmar contraseña",
         lastPassword: "contraseña actual",
         newPassword: "contraseña nueva",
         repeatNewPassword: "confirmar contraseña nueva",
         address: "colonia",
         userName: "nombre de usuario",
         name: "nombre(s)",
         firstName: "nombre(s)",
         lastName: "apellido(s)",
         secondName: "apellidos",
         diameter: "Diámetro del tronco",
         treeCanopyDiameter: "Diámetro de la copa",
         treeHeight: "Altura",
         height: "altura",
         ask:'Pregunta',
         answerA:'Respuesta opción A',
         answerB:'Respuesta opción B',
         answerC:'Respuesta opción C',
         answerD:'Respuesta opción D',
         explanation:'Breve explicación',
         photo:'Fotografía',
         titleReport: 'Título de tu reporte',
         report: 'Descripción del reporte',
         boundary: 'Colonia',
         street: 'Calle(s)',
         treeHeightMax: 'altura de árbol máxima',
         trunkDiameterMax: 'diámetro del árbol máxima',
         treeHeightMin: 'altura de árbol mínima',
         trunkDiameterMin: 'diámetro del árbol mínima',
         user: 'El campo {0} solo acepta las letras a-z minúsculas, los números del 0-9 y el guión bajo',
         passwordConfirm: 'La contraseña y su confirmación deben ser iguales',
         boundary: 'El campo colonia debe ser seleccionado del listado'
      },
      userTrees: {
         userTreesList: {
            title: "Mis árboles",
            messageHeaderFrag1: "Tienes un total de ",
            messageHeaderFrag2: "árbol(es) bajo tu cuidado",
            waterIn: "Regar en ",
            day: " día",
            days: " días",
            careToday: "¡Regar ahora!",
            type: 'Árbol adoptado',
            filter: 'Ordenar',
            emptyList: "No has adoptado árboles aún",
            filterLabel: 'Ordenar por',
            filterItemName: 'Nombre',
            filterItemDate: 'Fecha',
            noLabel: 'Sin especie'
         },
          userTreeView:{
            title: 'Ficha de árbol',
            dateCare: 'Bajo tu cuidado desde ',
            water:'Agua',
            photoSeason:'Foto estacional',
            days: ' días',
            day: ' día',
            drop: 'Regar',
            updatePhoto: 'Actualizar',
            treeCare:'Cuidado del árbol',
            messageTreeCareGood:'Has estado cuidando muy bien este árbol. ¡Sigue así! Y no olvides hacerlo en la vida real',
            detail: 'Ver ficha completa',
            report: 'Reportar árbol',
            continue: 'Continuar',
            treeCondition: 'Condición del árbol',
            realLife: 'En la vida real',
            question: '¿Cómo consideras que se encuentra el estado de conservación o salud del árbol?',
            dontSee:'No he visto mi árbol',
            messageTank: 'Gracias por ayudar a cuidar el arbolado de nuestra ciudad',
            messageReport: 'Al parecer el árbol no se encuentra bien. ¿Te gustaría levantar un reporte?',
            report: 'Reportar árbol',
            treeWatered: 'El árbol ha sido regado satisfactoriamente',
            waterMsg1: 'Tu árbol tiene suficiente agua, vuelve antes de {d} día(s) para mantenerlo en tu lista',
            waterMsg2: 'Riega tu árbol ahora, recuerda que tu árbol tiene suficiente agua para mantenerse {d} día(s)',
            waterMsg3: 'Riega tu árbol ahora si deseas mantenerlo en tu listado',
            changeSeason1:'Faltan {d} día(s) para el cambio de estación',
            changeSeason2:'Recuerda que tienes {d} día(s) para actualizar la foto estacional una vez se desbloquea esta función',
            changeSeason3:'Actualiza tu árbol ahora si deseas mantenerlo en tu lista',
            whPhotos: 'Sin fotografías estacionales'
         },
      },
      trivia: {
         title: 'Trivias',
         label: 'Puntos de experiencia',
         instructions01: 'Responde preguntas ',
         instructions02: 'y adquiere nuevos conocimientos sobre el ',
         instructions03: 'arbolado urbano',
         level: 'Nivel ',
         play:'JUGAR AHORA',
         create:'CREAR TRIVIA',
         empty: 'Al parecer no hay preguntas disponibles en este momento, intenta más tarde',
         leave: 'Salir',          
      },
      triviaCreate:{
        title: 'Creación de trivia',
        message:'A continuación listaremos los requerimientos para la creación',
        label:'Requerimientos:',
        continue:'Continuar',
        rule1:'Crear 5 preguntas relacionadas al arbolado urbano',
        rule2:'Subir una fotografía del árbol u hojas',
        rule3:'Agregar respuestas de selección multiple, considerar 1 respuesta correcta y 3 incorrectas'
      },
      triviaCreateForm:{
        title: 'Creación de trivia',
        question: "Pregunta ",
        the: ' de ',
        changePhoto: 'Cambiar fotografía',
        form:{
           question:'Pregunta*',
           answerA:"Respuesta opción A*",
           answerB:"Respuesta opción B*",
           answerC:"Respuesta opción C*",
           answerD:"Respuesta opción D*",
           optionA:"Opción A",
           optionB:"Opción B",
           optionC:"Opción C",
           optionD:"Opción D",
           correctAnswer:"Respuesta correcta*",
           explanation: "Breve explicación de la respuesta correcta",
           addphoto:"Agregar fotografía*",
           mandatory:"Los campos marcados con * son obligatorios",
           nextQuestion:"Siguiente pregunta",
           end: 'Finalizar',
           noOption: 'El campo "Respuesta correcta" es requerido',
           noPhoto: 'El campo "Fotografía" es requerido',           
        },
        pointsWon: '¡Ganaste ',
        pointsWon2: ' punto(s)!',
        pointsMsg: 'Gracias por capturar una nueva trivia',
        end: 'Finalizar',
        cancelAlert: '¿Deseas salir de la creación de trivia?',
        cancelMsg:'Al salir se perderán todos los cambios',
        cancel: 'Cancelar',
        confirm: 'Confirmar',
        retry: 'Intentar nuevamente',
        exit: 'Salir',
      },
      triviaAnswer:{
        title: 'Pregunta 1 de 5',
        next: 'Siguiente pregunta',         
        answered: 'Contestaste ',
        goodAnswer: ' pregunta bien',
        goodAnswers: ' preguntas bien',
        goodLuck: '¡Suerte para la próxima!',
        goodLuckMsg: 'No lograste conseguir puntos',
        cancelAlert: '¿Deseas salir de la trivia?',
        cancelMsg:'Al salir perderás la oportunidad de contestar las preguntas faltantes',
      },
      community:{
         title:'Comunidad',
         recent:'Reciente',
         outstanding: 'Destacado',
         toValidate: 'Por validar',
         tags: 'Etiquetas: ',
         threadClose: 'hilo cerrado',
         crateThread: 'Crear hilo',
         bottomOptionLayer:{
           outstanding:'Destacar esta publicación',
           noOutstanding:'No destacar esta publicación ',
           validate: 'Validar',
           close:'Cerrar hilo',
         },
         searchPlaceHolder: 'Buscar en comunidad',
         alerts:{
           sorry: 'Lo sentimos',
           limitThread: 'Al parecer ya creaste los hilos disponibles para esta semana',            
         },
         emptyList: "No hay resultados a mostrar para esta consulta",
         defaultPerm: 'No puedes realizar esta acción hasta el nivel 3'
      },
      communityCloseThread: {
        title:'Estás a punto de cerrar un hilo',
        message:'¿Cuál es la razón?',
        topicResolved:'Tema resuelto',
        innapropriateContent:'Contenido inapropiado',
        inactivity:'Inactividad',
        other: 'Otro',
        noSelected: 'Debes seleccionar la razón',
        noOther: 'Debes especificar la razón',
        close:'Cerrar hilo',
        closed: 'El hilo ha sido cerrado',
        end:'Finalizar',
        other: 'Ingresa el motivo'
      },
      communityFilters:{
         title: 'Filtros',
         showUserPublications: 'Mostrar mis publicaciones',
         byTag:'Por etiquetas',
         search: 'Buscar',
         cleanForm: 'Limpiar'
      },
      communityThread:{
         title:'Comunidad',
         recent:'Reciente',
         outstanding: 'Destacado',
         toValidate: 'Por validar',
         tags: 'Etiquetas: ',
         newComment: 'Escribe un comentario',
         alerts:{
            limit:{
              sorry: 'Lo sentimos',
              limitThread: 'Al parecer comentaste la cantidad de hilos disponibles para esta semana',
            },
            points:{
              pointsWon: '¡Ganaste ',
              pointsWon2: ' punto(s)!',
              pointsMsg: 'Gracias por contribuir a la comunidad',
              end: 'Finalizar',
            }
         },
      },
      communityThreadForm:{
        title:'Crear hilo',
        level: "Nivel: ",
        postNew: "Publica un nuevo hilo",
        addPhoto: "Agregar fotografía",
        changePhoto: "Cambiar fotografía",
        tags: "Etiquetas*",
        shared:'Compartir',
        validations:{
           noMessage:'Este campo es requerido',
           noTag:'Debes seleccionar al menos una etiqueta',
           mandatory:"Los campos marcados con * son obligatorios",
        },
        alerts:{
           pointsWon:'¡Ganaste ',
           pointsWon2:' punto! ',
           pointsMsg:'¡Gracias por aportar a la comunidad!',
           end:'Finalizar',
           cancel:'¿Deseas salir de la creación de un hilo?',
           cancelMsg: 'Al salir se perderán todos los cambios',
           cancelBtn: 'Cancelar',
           cancelConfirm: 'Confirmar',
        }
     },
     benefits: {
         colonyBenefits: "Beneficios de colonia",
         percentage: "%",
         engagedFirst: "Tu colonia es un ",
         engagedSecond: " más participativa que las colonias aledañas, sigan así.",
         dataQuestion: "¿Te gustaría conocer más datos sobre el arbolado urbano?",
         visitWebApp: "Visita nuestra aplicación web.",
         webApp: "Ir a aplicación web",
         share: "Compartir",
      },
      tree: {
         layersTitle: "Capas",
         layersDetailSubtitle: "Detalles del mapa",
         layersMapType: "Tipo de mapa",
         layersMapTypeButtonDefault: "Predeterminado",
         layersMapTypeButtonSat: "Satélite",
         addTreeTitle: "Capturar árbol",
         viewTreeTitle: "Árbol seleccionado",
         viewMultipleTreeTitle: "Hay {n} árboles capturados en la misma ubicación. Elige el árbol que deseas consultar. ",
         addTreeProcDescription: "Coloque el macador en la ubicación donde deseas capturar el árbol",
         addTreeContinueButton: "Continuar",
         takePhoto: "Tomar foto",
         ok: "Entendido",
         viewTreeButton: "Ver ficha",
         mapBar: {
            offline: "Mapa sin conexión",
            add: "Capturar",
            filters: "Filtrar especie"
         },
         emptyBoundaries: 'No hay conexión y no has descargado polígonos para su uso fuera de línea',
         selectBoundary: 'No hay conexión, selecciona uno de los polígonos descargados previamente para usar el modo offline',
         offlineLabel: 'Fuera de línea',
         onlineLabel: 'Modo online',
         exitMap: 'Salir del mapa',
         overlapPoint: 'Colocaste el marcador encima de un árbol existente, localízalo en alguna ubicación donde no haya algún punto',
         statusEditError: 'No puedes editar árboles completos o por validar, intenta con un árbol marcado como incompleto',
         statusLegendTitle: 'Estatus del árbol',
         statusComplete: 'Completo',
         statusValidating: 'Por validar',
         statusIncomplete: 'Incompleto',
         select: 'Selecciona'
      },
      treeForm: {
         title:'Formulario de árbol',
         titleEdit:'Editar un árbol',
         step: 'PASO',
         treeInformation: 'Información del árbol',
         photo: 'Fotografía',
         selectPhoto: 'Seleccionar foto',
         assistentSpecie: 'Asistente de selección de especie',
         assistentMeasure: 'Asistente de medición',
         addPhoto: 'Agregar fotografía',         
         specieLabel: 'Especie',
         specie: 'Selecciona una especie del listado o utiliza el asistente de selección',
         measuresLabel: 'Asigna las dimensiones del árbol, te recomendamos utilizar el asistente de medición',
         titleAssistant: "Selección de especie",
         noSpecie: 'No se encontró la especie',
         noSpecieSuggest: 'Te recomendamos tomar una foto y abrir un hilo en la sección de comunidad para que otros usuarios te ayuden a determinarla',
         changePhoto:'Actualizar foto',
         saveAndComeBack: 'Guardar y editar después',
         adoptAndValidate: 'Adoptar y enviar a validar',
         sendToValidate: 'Enviar a validar',
         save: 'Guardar',
         cancel: 'Cancelar',
         questionSave: '¿Qué te gustaría hacer con este árbol?',
         alertCancelTitle: '¿Deseas salir de la captura de árbol?',
         alertCancelText: 'Al salir se perderán todos los cambios',
         manualSpecie: 'Seleccionar especie manualmente',
         manualMeasures: 'Agregar medidas manualmente',
         measureError: 'Debes asignar las medidas del árbol antes de continuar',
         photoLabel:'Toma la mejor fotografía que puedas o selecciona una de tu galería',
         offlineConfirmationSave: "Tus datos se actualizaron de manera correcta en el almacenamiento local, recuerda sincronizar los datos una vez tengas conexión",
         confirm: 'Confirmar'

      },
      treeDetailFull:{
         title: 'Ficha de árbol',
         validateTitle: 'Validación de arbolado',
         treeAdopted: 'Árbol adoptado',
         treeIncomplete: 'Árbol incompleto',
         treeValidated: 'Árbol validado',
         treeDraft: 'Árbol por validar',
         treeInformation: 'Información del árbol',
         treeValidation: "Validar como correcto",
         treeEdit:"Editar información del árbol",  
         treeComments: "Observaciones",     
         specie:'Especie',
         treeID:'ID del árbol',            
         trunkDiameter:'Diámetro del tronco',
         trunkCircumference:'Circunferencia del tronco' ,
         treeCanopyDiameter: 'Diámetro de la copa',                     
         treeTopCircumference:'Circunferencia de la copa del árbol',
         treeHeight:'Altura',
         benefits: 'Beneficios',
         anualBenefits: 'Total de beneficios anuales',
         conservedEnergy: 'Energía conservada',
         ImprovedAirQuality:'Calidad del aire mejorada',
         co2Removed:'Dióxido de carbono eliminado',
         co2Storage:'Dióxido de carbono almacenado',
         stormWater:'Aguas pluviales filtradas',
         seasonalPhotos:'Fotos estacionales',
         share: 'Compartir',
         alerts:{
            points:{
              pointsWon: '¡Ganaste ',
              pointsWon2: ' punto!',
              pointsMsg: 'Validaste un árbol. ¡Gracias por tu aporte!',
              end: 'Finalizar',
            },
         },
         availableBenefits: 'Beneficios ambientales no disponibles para este árbol',
         yearSuffix: ' / año',
         toDateSuffix: ' a la fecha',
         noPhotos: 'Sin fotografías estacionales',
         adoptLabel: 'Adoptar árbol',
         viewPhotos: 'Ver fotos',
      },
      treePhotos: {
         currentPhoto: 'Foto actual',
      },
      treeFilters: {
        title: 'Filtros avanzados',
        rangeSeparator: 'hasta',
        measurePlaceholder: '0 m',
        treeHeight:'Altura del árbol',
        showWhitoutSpecies: 'Mostrar solo sin especies',
        showWhitoutDiameter: 'Mostrar solo sin diámetro del tronco',
        showWhitoutPhothos: 'Mostrar sin fotos',
        showInValidation: 'Mostrar solo por validar',
        chooseSpecieLabel: 'Selección de especies',
        specieDefaultLabel: 'Sin filtro',
        searchButton: 'Buscar',
        clearButton: 'Limpiar',
        minMaxValue: 'Verifica el valor mínimo y máximo'
      },
      treeComments:{
         title:'Observaciones',
         desc: 'Selecciona la observación que deseas realizar',
         descLong:'Recuerda que las observaciones son sobre los datos capturados en la ficha, para levantar un reporte utiliza el módulo de reportes',     
         placeholder: '' ,
         noOther: 'El campo observación no puede estar vacío',
         success: 'Gracias por enviar la observación',
         save: 'Guardar',
         INCORRECT_SPECIE: "Especie incorrecta",
         INCORRECT_MESAURES: "Mediciones incorrectas",
         INCORRECT_PHOTO: "Foto incorrecta o inapropiada",
         TREE_NOT_FOUND: "Árbol inexistente",
         OTHER: "Otro",
         otherDesc: 'Ingresa la observación',
         noSelected: 'Debes seleccionar una observación',
      },
      specieAssistant: {
         searchPlaceHolder: 'Buscar especie',
         selectSpecieText: 'Bienvenido al asistente de selección de especies de árboles comunes',
         asignSpecie: 'Asignar especie',
         specieNotFound: 'No encontré la especie',
         showOnlyCommonSpecies: 'Mostar solo especies comunes'
      },
      cameraAssistant: {
         title: 'Asistente de medición',
         permissionTitle: 'Permisos de asistente de medición',
         message: 'El asistente requiere permisos para obtener la foto de referencia',
         buttonNeutral: 'Preguntar más tarde',
         buttonNegative: 'Cancelar',
         buttonPositive: 'Aceptar',
         welcome: 'Bienvenido al asistente de medición de árboles',
         slide1: 'Coloca al lado del árbol un objeto o persona de referencia del que conozcas su altura y toma una fotografía. Es necesario que aparezca el árbol completo',
         slide2: 'Traza la altura de tu objeto o persona de referencia',
         slide3: 'Ingresa la altura del objeto o persona que tomaste de referencia en metros',
         slide4: 'Traza una línea vertical de un extremo a otro para marcar la altura del árbol y una línea horizontal para marcar el ancho de la copa y tronco',
         slide5: 'Las dimensiones del árbol han sido calculadas automáticamente',
         slide6:  'Traza la altura del árbol',
         slide7:  'Traza el ancho del tronco',
         slide8:  'Traza el ancho de la copa',
         slide9:  'Traza una línea vertical desde la base del objeto o persona hasta donde termina',
         slide10: 'Traza una línea vertical desde la base hasta la punta más alta del árbol',
         takePhotoDesc: 'Toma la foto, es necesario que aparezca el árbol completo',
         orientationAlert: 'Para utilizar este asistente tienes que posicionar tu dispositivo siempre en modo vertical o en modo portaretratos',
         pinchDesc1:'Traza la línea indicada en pantalla',
         pinchDesc2:'Puedes ajustar el tamaño y mover la línea a cualquier parte de la pantalla'
      },
      treeOffline: {
         title: "Mapas sin conexión",
         donwlonadPolygon: "Colonias descargadas",
         placeholderSearch: 'Buscar polígono',
         history: "Historial",
         seeMore: "Ver más",
         details: "Detalles",
         downloadDate: "Fecha de descarga: ",
         downloading: "Descargado",
         editedTrees: "Árboles editados: ",
         treeTotal: "Total de árboles: ",
         download: "Descargar",
         actions: "Acciones realizadas",
         lastUpdated: "Fecha de última actualización",
         capturedTrees: "Árboles capturados: ",
         secondEditedTrees: "Árboles editados: ",
         adoptedTrees: "Árboles adoptados: ",
         sync: "Sincronizar",
         successfulSync: "¡Sincronización exitosa!",
         conflict: "Al parecer otro usuario capturó o editó el mismo árbol que tú",
         solve: "Ver anomalias",
         dateCaptured: "Fecha de captura",
         discardTree: "Descartar árbol",
         duplicateRecords: "Registros repetidos",
         end: "Finalizar",
         emptyList: 'No has descargado polígonos aún',
         downlaodMessage: "Polígono descargado satisfactoriamente",
         errorDownlaodMessage: "Error al descargar polígono, vuelve a intentarlo o regresa más tarde",
         deleteText: "Al presionar el botón continuar se eliminará el polígono local y todos los puntos que no hayas sincronizado, se recomienda sincronizar de manera constante y eliminar los polígonos que no utilices para ahorrar espacio",
         dateLabel: 'Fecha de descarga: ',
         modifications: 'Modificaciones:',
         remaining: 'Restantes a sincronizar:',
         synchronized: 'Sincronizados:',
         conflicts: 'Conflictos:',
         pause: 'Pausar',
         sync: 'Sincronizar',
         continue: 'Continuar',
         delete: 'Eliminar',
         conflictLog: 'Log de conflictos'
      },
      forgotPassword: {
         description: "Ingresa tu cuenta de correo electrónico y te enviaremos el enlace de recuperación de contraseña",
         email: "Correo electrónico",
         recoverPassword: "Recuperar contraseña",
         cancel: "Cancelar",
         emailSent: "Se te ha enviado un correo con los pasos a seguir para efectuar la recuperación de tu contraseña",
         continue: "Continuar",
         sendAgain: "Enviar de nuevo"
      },
      friends: {
         friends: "Amigos",
         followers: "Seguidores",
         following: "Siguiendo",
         unfollow: "Dejar de seguir",
         insignias: "Insignias",
         achievements: 'Logros',
         trees: "Árboles",
         global: "Global",
         level: "Nivel: ",
         followsYou: "Te sigue",
         follow: "Seguir",
         stopFollowing: "¿Dejar de seguir?",
         cancel: "Cancelar",
         confirm: "Confirmar",
         search: "Buscar amigos",
         emptyListFollowers: "No tienes seguidores",
         emptyListFollowing: "No sigues a nadie. ¡Encuentra amigos, compite y colabora en la comunidad!",
         emptyListGlobal: "¡Vaya, parece que no hay usuarios registrados!",
         emptySearchResult: "No se han encontrado resultados",
         xp:'Puntos de experiencia:',
         messageFriendAdded: 'Acción realizada, sigue a otros usuarios para hacer comunidad' 
      },
      logIn: {
         userName: "Nombre de usuario",
         password: "Contraseña",
         logIn: "Iniciar sesión",
         or: "o inicia sesión con",
         forgotPassword: "Olvidé mi contraseña",
         register: "Registrarse",
         facebook: "Iniciar sesión con Facebook",
         google: "Iniciar sesión con Google",
         error: {
            badCredentials: "Nombre de usuario o contraseña incorrectos"
         }
      },
      promoteUsers: {
         promoteUsers: "Ascender usuarios",
         candidates: "Candidatos",
         proUsers: "Usuarios PRO",
         seeCard: "Ver ficha",
         userAchievements: "Logros del usuario",
         followers: "Seguidores",
         plantedTrees: "Árboles plantados",
         posts: "Publicaciones",
         promoteToPro: "Convertir en usuario PRO",
         promotionConfirmation: "¿Estás seguro que quieres convertir a este usuario a PRO?",
         PROPermissions: "Al confirmar tendrá permiso de realizar las siguientes acciones:",
         permission1: "-Ascender usuarios",
         permission2: "-Validación de árboles",
         permission3: "-Creación de trivias",
         permission4: "-Moderador en la sección de comunidad",
         demote: "Deshabilitar como Usuario PRO",
         demoted: "Has deshabilitado al usuario:",
         inform: "Le enviaremos una notificación para informarle.",
         end: "Finalizar",
         aboutToDemote: "Estás a punto de deshabilitar a un usuario PRO",
         reason: "¿Cuál es la razón?",
         fakeNews: "Creación de contenido falso",
         inactivity: "Inactividad",
         other: "Otro:",
         continue: "Continuar",
         search: "Buscar",
         level: "Nivel: ",
         emptyNoPro: "No se encontraron candidatos",
         emptyPro: "No se han agregado usuarios PRO"
      },
      promoteUserCancel:{
        title: "Deshabilitar usuario PRO",
        disable:'Deshabilitar',
        closed: 'El usuario ha sido deshabilitado',
        other: 'Otro'
      },
      register: {
         title: "Registro",
         email: "Correo electrónico*",
         lastPassword: "Contraseña actual",
         password: "Contraseña*",
         newPassword: "Contraseña nueva",
         repeatPassword: "Confirmar contraseña*",
         repeatNewPassword: "Confirmar contraseña nueva",
         userName: "Nombre de usuario*",
         name: "Nombre*",
         firstName: "Nombre*",
         lastName: "Apellido*",
         secondName: "Apellidos*",
         address: "Colonia*",
         organization: "Organización",
         inviteCode: "Código de invitación",
         codeExplanation: "\nCuando un amigo te invite a utilizar la aplicación puedes insertar aquí su código de invitación, al ingresar el código de tu amigo lo estás ayudando a recibir más puntos, si no tienes un código simplemente ignora este campo.",
         continue: "Continuar",
         register: "Registrarse",
         save: "Guardar",
         cancel: "Cancelar",
         required: "Los campos marcados con * son obligatorios",
         uexist: "Ya existe un usuario con el correo o nombre de usuario dado"
      },
      legalAgreements: {
         title: "Legales",
         termsAndConditions: "Términos y condiciones",
         privacyPolicy: "Política de privacidad",
         accept: "Aceptar condiciones de uso y políticas de privacidad",
         continue: "Continuar",
      },
      successfulRegistration: {
         successfulRegistration: "¡Registro exitoso!",
         accountRegistrated: "La cuenta ha sido registrada correctamente",
         continue: "Continuar"
      },
      userProfile: {
         level: "Nivel",
         myContribution: "Mi contribución",
         contributionMessage: "Acciones realizadas esta semana",
         more: "Ver más",
         benefits: "BENEFICIOS",
         myTrees: "MIS ÁRBOLES",
         friends: "AMIGOS",
         insignia: "INSIGNIAS",
         levelsList: "Listado de niveles",
         xp: 'Puntos de experiencia:',
      },
      userLevels: {
         title: "Niveles",
         level: "Nivel:"
      },
      insignia:{
         title: "Insignias",
         lastAchievement: "Último logro",
         unlocked: "OBTENIDA",
         locked: "BLOQUEADA",
         emptyList: "No se encontraron resultados",
      },
      editProfile: {
         title: "Editar perfil",
         changePhoto: "Cambiar foto de perfil",
         cancelPhoto: "Cancelar",
         library: "Galería",
         camera: "Cámara",
         changePass: "Cambiar contraseña",
         confirmationSave: "Tus datos se actualizaron de manera correcta",
         offlineConfirmationSave: "Tus datos se actualizaron de manera correcta en el almacenamiento local, recuerda sincronizar los datos una vez tengas conexión",
         confirmationAdoption: "Árbol adoptado, puedes revisar el estado de tu nuevo árbol en el apartado mis árboles",
         continue: "Continuar",
         errorNewPass: 'Las nuevas contraseñas deben ser iguales',
      },
      treesValidation:{
         title: 'Validación de arbolado',
         createDate: 'Fecha de creación:',
         treeValidate: "Árbol por validar",
         noSpecie: 'Sin especie',
         emptyList: "No hay resultados a mostrar para esta consulta",
         filter: 'Ordenar',
         filterLabel: 'Ordenar por',
         filterItemName: 'Nombre',
         filterItemDate: 'Fecha',
         dateOrder: 'Ordenar por fecha'
      },
      treesEditedByCurrentUser:{
         title: 'Mis ediciones',
         createDate: 'Fecha de creación:',
         modificationDate: 'Última modificación:',
         treeValidate: "Árbol por validar",
         noSpecie: 'Sin especie',
         emptyList: "No has capturado o editado árboles",
         filter: 'Ordenar',
         filterLabel: 'Ordenar por',
         filterItemName: 'Nombre',
         filterItemDate: 'Fecha',
         dateOrder: 'Ordenar por fecha'
      },
      userReports:{
         title: 'Reportes',
         publishDate:"Fecha de creación: ",
         create:'Crear reporte',
         alerts:{
            sorry: 'Lo sentimos',
            limitThread: 'Al parecer ya creaste los reportes disponibles para esta semana',            
          },
         open: 'En proceso',
         close:'Cerrado',
         emptyList: "No has enviado reportes aún",
      },
      report:{
         title: 'Ficha de reporte',         
         description: 'Descripción del reporte',
         boundary: 'Colonia',
         publishDate:'Fecha de creación',
         tags:'Etiquetas',
         location:'Ubicación',
         open: 'En proceso',
         close:'Cerrado',
       },
      reportForm:{
         title:'Levantamiento de reportes',
         message1: 'En esta sección podrás hacer reportes sobre el arbolado urbano',
         message2: '¡Procura tomar una buena fotografía!',
         mapIndication:'Presiona el marcador durante unos segundos y muévelo a la ubicación del árbol a reportar',
         reportTitle: 'Título de tu reporte*',
         street: 'Calle(s)*',
         boundary:'Colonia*',
         reportPlaceHolder: 'Cuéntanos qué sucede con este árbol*',
         addPhoto:'Agregar fotografía*',
         tags: 'Etiquetas*',
         report: 'Reportar',
         boundaryPlaceholder: "Buscar colonia",
         validations:{
            noPhoto:'Debes añadir una foto a tu reporte',
            noTag:'Debes seleccionar al menos una etiqueta',
            noBoundary:'El campo "Colonia" es requerido',
            mandatory:"Los campos marcados con * son obligatorios",
         },
         alerts:{
            pointsWon:'¡Ganaste ',
            pointsWon2:' punto(s)! ',
            pointsMsg:'¡Gracias por tu reporte!',
            end:'Finalizar',
            cancel:'¿Deseas salir del levantamiento de reporte?',
            cancelMsg: 'Al salir se perderán todos los cambios',
            cancelBtn: 'Cancelar',
            cancelConfirm: 'Confirmar',
         }
      },
      notifications:{
         title: 'Notificaciones',
         LOGIN: 'INICIO DE SESIÓN',
         VIEW_ON_BOARD: 'TUTORIAL',
         SKIP_ON_BOARD: 'TUTORIAL',
         ADD_TREE: 'ARBOLADO',
         EDIT_TREE: 'ARBOLADO',
         ADOPT_TREE: 'MIS ÁRBOLES',
         VALIDATE_TREE: 'ARBOLADO',
         UPDATE_PHOTO: 'ARBOLADO',
         WATER_TREE: 'MIS ÁRBOLES',
         ADD_COMMUNITY_PUBLICATION: 'COMUNIDAD',
         ADD_COMMUNITY_COMMENT: 'COMUNIDAD',
         ANSWER_QUESTION_CORRECTLY:'TRIVIA',
         ADD_TRIVIA:'TRIVIA',
         ADD_FRIEND:'USUARIOS',
         ADD_REPORT:'REPORTES',
         DEFAULT:'ÁRBOL IOT',
         emptyList: 'Bandeja de notificaciones vacía'
      },
      main: {
         selectLocation: 'SELECCIONAR LOCALIZACIÓN',
         trees: "Árboles",
         airQuality: "calidad del aire",
         humidity: "humedad",
         urbanTrees: "CAPTURA Y CONSULTA DEL ARBOLADO URBANO",
         community: "COMUNIDAD",
         benefits: "BENEFICIOS",
         myTrees: "MIS ÁRBOLES",
         trivia: "TRIVIA",
      },
      userContribution:{
         title: "Mi contribución",
         messageBad: "Esta semana tuviste un malo compromiso con el medio ambiente",
         messageGood: "Esta semana tuviste un bueno compromiso con el medio ambiente",
         messageExcelent: "Esta semana tuviste un excelente compromiso con el medio ambiente",
         activities: "Actividades realizadas esta semana: ",
         mainMessage: "Has obtenido {n} / 100 puntos de participación, este indicador se calcula partiendo de las interacciones semanales realizadas por todos los usuarios activos en la plataforma"
      },
      boundary: {
         title:'Colonias favoritas',
         addColony: 'Agregar colonia',
         description: 'Árboles por colonia',
         delete: 'Eliminar',
         deleteMessage: '¿Estás seguro que deseas eliminar a esta colonia de tu listado de favoritos?',
         confirm: 'Aceptar',
         add: 'Añadir',
         addedMessage: 'Se ha agregado una nueva colonia al listado de favoritos',
         continue: 'Continuar',
         emptyList: 'No has agregado colonias',
         searchPlaceholder: 'Ingresa un criterio de búsqueda'
      },
      gamificaitionAlert: {
         unlock:'¡Logro desbloqueado!',
         levelReached: 'Alcanzaste un nuevo nivel',
      },
      sideMenu: {
         level: "Nivel: ",
         seeProfile: "Ver perfil",
         citizenReports: "Reportes ciudadanos",
         treeValidation: "Validación de arbolado",
         promoteUsers: "Ascender usuarios",
         settings: "Configuración",
         termsAndConditions: "Legales",
         logOut: "Cerrar sesión",
         completeMode: "Activar modo completo",
         liteMode: "Activar modo lite"
      },
      onBoard: {
         skip: 'Saltar',
         next: 'Siguiente',
         points: 'Gracias por tomar este pequeño tutorial. ¡Ahora a capturar árboles!'
      }
    },
    en: {
    }
});


strings.setLanguage('es');

export default strings;