
export const LOGIN = "SET_LOGGED_IN_STATE";   
export const UPDATE_USER = "SET_USER_UPDATE"; 
export const CHANGE_MODE = "CHANGE_MODE"; 
export const LOGOUT = 'CLEAR_SESION';
export const RECOVER = 'RECOVER_STATE';
export const SET_CONFIG = 'SET_CONFIG';
export const SET_MEASURE = 'SET_MEASURE';
export const SET_LAST_MAIN_DATA = 'SET_LAST_MAIN_DATA';
export const UPDATE_NOTIFICATIONS_INDICATOR = 'UPDATE_NOTIFICATIONS_INDICATOR';
export const SET_ALERT_STATE = 'SET_ALERT_STATE';
export const SET_PARAM = 'SET_PARAM';
export const SYNC_BOUNDARY_FAVS = 'SYNC_BOUNDARY_FAVS';
export const SET_CURRENT_BOUNDARY = 'SET_CURRENT_BOUNDARY';
export const SAVE_LOCAL_BOUNDARY = 'SAVE_LOCAL_BOUNDARY';
export const REMOVE_LOCAL_BOUNDARY = 'REMOVE_LOCAL_BOUNDARY';
export const ADD_TREE_TO_LOCAL_REPOSITORY = 'ADD_TREE_TO_LOCAL_REPOSITORY';
export const PROFILE = 'SET_PROFILE_IN_STATE';



